# Generated by Django 3.2.8 on 2021-10-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=154)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
            ],
        ),
    ]
