# Generated by Django 3.2.8 on 2021-11-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='path',
            field=models.CharField(choices=[('AWS-DevOps', 'AWS-DevOps'), ('Full Stack', 'Full Stack'), ('Data Science', 'Data Science')], max_length=50),
        ),
    ]
